
image: "python:3.7"

before_script:
  - python --version
  - pip install gitbuilding

pages:
  stage: deploy
  script:
  - gitbuilding build
  - gitbuilding build-html
  - mv _site public
  # gzip the files so we get compression in gitlab pages
  - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master

